//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_StokTakip.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Kullanicilar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanicilar()
        {
            this.Sepet = new HashSet<Sepet>();
        }

        public int ID { get; set; }
        [Required(ErrorMessage = "Boþ Geçilemez")]
        public string KullaniciAdi { get; set; }
        [Required(ErrorMessage = "Boþ Geçilemez")]
        public string Sifre { get; set; }

        public string Rol { get; set; }
        [Required(ErrorMessage = "Boþ Geçilemez")]
        public string AdiSoyadi { get; set; }
        [Required(ErrorMessage = "Boþ Geçilemez")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$",
                   ErrorMessage = "Uygun formatta telefon numarasý giriniz.")]
        public string Telefon { get; set; }
        [Required(ErrorMessage = "Boþ Geçilemez")]
        public string Adres { get; set; }
        [Required(ErrorMessage = "Boþ Geçilemez")]
        [DataType(DataType.EmailAddress)]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$",
            ErrorMessage = "Lütfen uygun formatta e-mail adresi giriniz.")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Boþ Geçilemez")]
        public System.DateTime Tarih { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sepet> Sepet { get; set; }
    }
}
