//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_StokTakip.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Musteriler
    {
        [Required(ErrorMessage = "Boþ Býrakýlamaz")]
        public int ID { get; set; }
        [Required(ErrorMessage = "Boþ Býrakýlamaz")]
        public string AdiSoyadi { get; set; }
        [Required(ErrorMessage = "Boþ Býrakýlamaz")]
        public string Telefon { get; set; }
        [Required(ErrorMessage = "Boþ Býrakýlamaz")]
        public string Adres { get; set; }
        [Required(ErrorMessage = "Boþ Býrakýlamaz")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Boþ Býrakýlamaz")]
        public string Resim { get; set; }
        [Required(ErrorMessage = "Boþ Býrakýlamaz")]
        public System.DateTime KayitTarihi { get; set; }
        [Required(ErrorMessage = "Boþ Býrakýlamaz")]
        public decimal Puani { get; set; }
        [Required(ErrorMessage = "Boþ Býrakýlamaz")]
        public string Aciklama { get; set; }
    }
}
