//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_StokTakip.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Sepet
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Boþ Býrakýlamaz")]
        public int UrunID { get; set; }
        [Required(ErrorMessage = "Boþ Býrakýlamaz")]
        public decimal BirimFiyati { get; set; }
        [Required(ErrorMessage = "Boþ Býrakýlamaz")]
        public decimal Miktari { get; set; }
        [Required(ErrorMessage = "Boþ Býrakýlamaz")]
        public decimal ToplamFiyati { get; set; }
        [Required(ErrorMessage = "Boþ Býrakýlamaz")]
        public System.DateTime Tarih { get; set; }
        [Required(ErrorMessage = "Boþ Býrakýlamaz")]
        public System.DateTime Saat { get; set; }
        [Required(ErrorMessage = "Boþ Býrakýlamaz")]
        public int KullaniciID { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
